module.exports = {
  RATE_LIMITER: 'Число запросов с одного IP в единицу времени ограничено',
  SERVER_500_ERROR: 'На сервере произошла ошибка',
  NOT_FOUND_RESOURCE: 'Запрашиваемый ресурс не существует',
  NOT_FOUND_ID: 'Нет данных по переданному id',
  INCORRECT_MAIL_FORMAT: 'Неправильный формат почты',
  INCORRECT_EMAIL_OR_PASSWORD: 'Неправильные почта или пароль',
  INVALID_IMAGE_URL: 'Некорректный url изображения',
  INVALID_TRAILER_URL: 'Некорректный url трейлера',
  INVALID_THUMBNAIL_URL: 'Некорректный url миниатюры',
  AUTHORIZATION_REQUIRED: 'Необходима авторизация',
  USER_IS_NOT_UNIQUE: 'Пользователь с таким email уже зарегестрирован',
  INVALID_URL: 'Некорректный URL',
  DELETE_OTHER_MOVIE: 'Нельзя удалить чужой фильм',
};
